# GitHub Sponsors
# 如果你想接受赞助，取消注释并修改下面的链接：
# custom: ["https://github.com/sponsors/alijiujiu123"]

# 或者使用其他赞助平台：
# github: [你的 GitHub 用户名]
# patreon: 你的用户名
# open_collective: 你的组织名
# ko_fi: 你的用户名
# tidelift: # 你在 tidelift 上的包名
# community_bridge: # 你的项目名
# liberapay: 你的用户名
# issuehunt: 你的仓库
# otechie: 你的用户名
